### ISSUE TITLE
"Generated bad bytecode" Error

### ISSUE THREAD

**Issue by Lucraft** [unnamed/mocha#5]
Hi, been trying to integrate Mocha into a project, and run into this error:

```
java.lang.IllegalStateException: Generated bad bytecode, open an issue at https://github.com/unnamed/mocha/issues
	at team.unnamed.mocha.runtime.MolangCompiler.compile(MolangCompiler.java:211) ~[mocha-3.0.0-SNAPSHOT.jar:?]
	at team.unnamed.mocha.MochaEngineImpl.compile(MochaEngineImpl.java:185) ~[mocha-3.0.0-SNAPSHOT.jar:?]
	at team.unnamed.mocha.MochaEngine.compile(MochaEngine.java:252) ~[mocha-3.0.0-SNAPSHOT.jar:?]
	at net.threetag.palladium.client.dynamictexture.variable.EntityTicksTextureVariable$Serializer.parse(EntityTicksTextureVariable.java:33) ~[main/:?]
	at net.threetag.palladium.client.dynamictexture.DynamicTexture.parse(DynamicTexture.java:111) ~[main/:?]
	at net.threetag.palladium.util.SkinTypedValue.fromJSON(SkinTypedValue.java:68) ~[main/:?]
	at net.threetag.palladium.client.renderer.renderlayer.PackRenderLayer.parse(PackRenderLayer.java:134) ~[main/:?]
	at net.threetag.palladium.client.renderer.renderlayer.PackRenderLayerManager.parseLayer(PackRenderLayerManager.java:134) ~[main/:?]
	at net.threetag.palladium.client.renderer.renderlayer.PackRenderLayerManager.lambda$apply$4(PackRenderLayerManager.java:112) ~[main/:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at net.threetag.palladium.client.renderer.renderlayer.PackRenderLayerManager.apply(PackRenderLayerManager.java:110) ~[main/:?]
	at net.threetag.palladium.client.renderer.renderlayer.PackRenderLayerManager.apply(PackRenderLayerManager.java:37) ~[main/:?]
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.method_18790(SimplePreparableReloadListener.java:19) ~[minecraft-merged-381da26455-1.20.1-loom.mappings.1_20_1.layered+hash.434613298-v2.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire$$$capture(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.method_18365(SimpleReloadInstance.java:83) ~[minecraft-merged-381da26455-1.20.1-loom.mappings.1_20_1.layered+hash.434613298-v2.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:143) ~[minecraft-merged-381da26455-1.20.1-loom.mappings.1_20_1.layered+hash.434613298-v2.jar:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[minecraft-merged-381da26455-1.20.1-loom.mappings.1_20_1.layered+hash.434613298-v2.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:114) ~[minecraft-merged-381da26455-1.20.1-loom.mappings.1_20_1.layered+hash.434613298-v2.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:103) ~[minecraft-merged-381da26455-1.20.1-loom.mappings.1_20_1.layered+hash.434613298-v2.jar:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1111) ~[minecraft-merged-381da26455-1.20.1-loom.mappings.1_20_1.layered+hash.434613298-v2.jar:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:731) ~[minecraft-merged-381da26455-1.20.1-loom.mappings.1_20_1.layered+hash.434613298-v2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:229) ~[minecraft-merged-381da26455-1.20.1-loom.mappings.1_20_1.layered+hash.434613298-v2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]
	at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:219) ~[architectury-transformer-5.2.81-runtime.jar:?]
Caused by: javassist.bytecode.BadBytecode: stack underflow at 12
	at javassist.bytecode.CodeAnalyzer.visitBytecode(CodeAnalyzer.java:86) ~[javassist-3.30.1-GA.jar:?]
	at javassist.bytecode.CodeAnalyzer.computeMaxStack(CodeAnalyzer.java:50) ~[javassist-3.30.1-GA.jar:?]
	at javassist.bytecode.CodeAttribute.computeMaxStack(CodeAttribute.java:251) ~[javassist-3.30.1-GA.jar:?]
	at team.unnamed.mocha.runtime.MolangCompiler.compile(MolangCompiler.java:208) ~[mocha-3.0.0-SNAPSHOT.jar:?]
	... 28 more
```

The MoLang function it's trying to compile is the following: `math.mod(value / 20, 3)`.

In code I'm doing this:
```java
String function = GsonHelper.getAsString(json, "function", null);

return new EntityTicksTextureVariable(AbstractIntegerTextureVariable.parseOperations(json),
                    function != null ? MochaEngine.createStandard().compile(function, MoLangIntFunction.class) : null);
```

```java
public interface MoLangIntFunction extends MochaCompiledFunction {

        int get(@Named("value") int value);

}
```

**Comment by yusshu** [comment]
Fixed in 90a08a9a01d1b28a53a8de1046a290e5baaccf42
